
import React from 'react'

function HomeNew() {
  return (
    <div>
      <div className="container-fluid">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-8 al"></div>
  <div class="d-grid gap-2">
  <h2 className='text-dark'> Are you currently enrolled in Medicare?</h2>
  <button class="btn btn-primary" type="button">Button</button>
  <button class="btn btn-primary" type="button">Button</button>
</div>
    </div>
    </div>
    </div>
    </div>
  )
}

export default HomeNew